### PR TITLE
forgot to install prades locally

### PR DESCRIPTION
**Pull request by krunal-patel-fl4re**

### CODE REVIEW

**Review by rbourianes — APPROVED** [review]

**Comment by TrustNik** [comment]
@krunal-patel-fl4re @mbarnes-sb 
Can we please stop doing it?
It was discussed many times already - there is 2 ways of handling prades dependency:
1. Add it to package.json making it a local dependency. This is the way 99.99% packages in npm does work.
2. Manually install it on each node as global dependency - the way it currently works for the engine. This is obviously a busywork as it requires devops to handle everything manually. We have a proof that this process does not scale. (Prades update from 0.3.9 to 0.4.0 has not been done in 2 months).
And that is because everything is tight into devops - and I understand you guys are busy right now.

So what we need is to switch to option 1 to let anyone send a PR for updates and stop making devops a bottleneck.

The way it is implementing right now in this 2 PRs is no go. Its using local dependency that is not listed in the package.json and installed on the fly. And btw its installing latest version so all the "we need global install to handle consistency across packages" is just not working.

cc @borisbat @Olivier-Berteil-SB

**Comment by krunal-patel-fl4re** [comment]
If I recall correctly, the Prades discussion we talked about before was how it would be used by clients on the receiving end of an already published package.  The work I’m doing now is for publishing a new package.

**Comment by TrustNik** [comment]
Looks like there is no undetstanding on devops side of how npm packages are working. Lets have meeting so we can discuss the subject.

**Comment by krunal-patel-fl4re** [comment]
This PR is about publishing to prades and how it could be installed for that (new) use case.  The "discussed many times" you broadly refer to has been about how prades could be installed when grabbing artifact packages off prades and installing the package in question.  I see those as 2 different cases from DevOps perspective since we may possibly have different agents fulfilling each of them and how prades may be installed wrt that.  We've been taking this approach since our first prades published package, starvr-sdk.  If there is an area of improvement/consolidation that can be made, lets do so.

**Pull request merged**
